### ISSUE TITLE
suggections

### ISSUE THREAD

**Issue by azjezz** [darklightcode/PHP-Built-in-web-server-Router#1]
i started using this router for test about 2 weeks ago cause apache crashed, tbh this is a really good router for php, but the code is not organized, you should split the router class into multiply class, a class have 1 job. 
you may also use some packages and make it a php cli application.

**Comment by darklightcode** [comment]
I started this project with separate class files, but in the long run i realized that being too organized for a php router isn't too helpful since i didn't want anyone that uses this router, especially newcomers to php, to get stuck with the required files, or copy/pasting them etc, and i've decided to keep it simple.
There are several router files out there but i couldn't find one "cross-frameworks", so those messy code parts i wrote are for some of the frameworks i added in README.md .

I like the idea of a php cli application so i will mark this issue as an Enhancement.
I don't have time to make changes now, quite busy at work, but i guess in about two weeks i'll manage to do it.

PS: If you're the NodeJS/JS/PHP type of guy, give a try to [node-php-awesome-server](https://www.npmjs.com/package/node-php-awesome-server), it's a webserver that uses this router and bypasses the "single-thread" limitation of a php router using workers. I use it everyday in a team environment with php + webpack + hmr and it works great.

**Comment by azjezz** [comment]
i don't use NodeJS, i'm quite busy now, but maybe next week I'll pull a request separating the router.class.php into multiple classes, then it can be used to create an cli application

**Comment by azjezz** [comment]
also, you may add a psr_4 autoloader inside it , so it can autoload php files and show logs in the console.

**Comment by azjezz** [comment]
but its not really a good idea, since every application should have its own autoloader

**Comment by azjezz** [comment]
i think these packages can be used to make a really good php cli router application 

https://github.com/symfony/finder
https://github.com/symfony/http-foundation
https://github.com/symfony/yaml
https://github.com/symfony/console


- the router should have a config file next to index.php `router.yaml`

Router.yaml example : 

```
Host: localhost
Port: 80

# whether to send 'SERVER' header or not 
signature: false

# Error documents 
ErrorDocument:
    404: path/to/404.html
    403: path/to/403.html
    500: path/to/500.html

# Log files
Log: true
LogFile: mylogs
LogErrors: true
LogErrorsFile: myerrorlogs

# Headers to be sent after processing the request and before sending the body
Headers:
    x-xss-protection: 1; mode=block
    x-content-type-options: nosniff
    x-frame-options: SAMEORIGIN

# Whether to use rewrite engine or not
# if this is set to false, a request to none existing file shall return a 404 error
# and send the 404 error document if specified or a default 404 page 
RewriteEngine: true
RewriteIndex: index.php

# any request sent to the next files/directories should return a 403 error
# and send the 403 error document if specified or a default 403 page
lock: 
    -
        file: router.yaml
    - 
        file: mysecert.txt
    - 
        dir: source
    - 
       dir: images/admin

```

Project structure example : 
```
project /
    app/ 
    lib/
        vendor/
    web / 
        js / 
            example.js
            app.js
        css/
            style.css
            style.less
        images/
            admin/ #403 error
                 adminInShower.png # 403 error
            image.png
        index.php
        router.yaml # 403 error
        
```

commands : 

`$ php-router start`
start the php built-in server with the router and configurations from router.yaml, if no configuration file is found use the default configurations 
( this also opens a second cli window to monitor requests and errors ) 
`$ php-router stop`
stops the server 
`$ php-router logs`
shows last 100 lines in the log file 
`$ php-router logs 500`
shows last 500 lines in the log file
`$ php-router logsdir`
shows the log file directory 

the last 3 commands shall be applied to error logging ( replace `log` with `errorlog`)

the router should rewrite urls to remove trailing slash from  path
example: `localhost/images///image.png` redirects to  `localhost/images/image.png`

Request handling : 

Request: `GET http://localhost/home`
$path = '/home';
// this can be made simple with symfony/finder
if(is_file($path))
{
   the file should be returned 
} elseif (is_dir($path) && hasIndex($path)) {
   return the directory index
} elseif($config->rewriteEngine) {
   return the index specified in config ( $config->rewriteIndex ) or default 'index.php'
} else {
   return 404
}

Request: `http://localhost/router.yaml`
the should return a 403 error

**Comment by darklightcode** [comment]
This looks great, looking forward to see a PR, just make it simple for now, don't overthink it because the php built-in webserver has it's ways to interpret things. I will make a list later today with some targets that must be reached and some bugs that i encountered while developing this.

I need to point out that while i like the router.yaml idea, it should be moved in the root folder ("project/") not in the web/ folder , we could easily add another option in config like " public : path/to/web/ ". Development files should be kept away from public folders and we can start the webserver from the root folder  `/project>php-router start` or some `/project>php-router start --config="./devFiles/router.yaml"` if router.yaml is placed somewhere else.

**Comment by azjezz** [comment]
i'm gonna start working on it now ! the php server in gonna be running as a background processor and the output can be write to the log file directly.
example : https://stackoverflow.com/questions/45953/php-execute-a-background-process.

command: `$ router monitor`
opens a second command line to monitor the web server logs 
opening a second command line in windows via php can be done like this : 
`exec('start cmd.exe @cmd /k php -r \"while (true) { echo 1 . PHP_EOL; sleep(1); }\" ');`
try opening cmd in windows and run : 
`php -r "exec('start cmd.exe @cmd /k php -r \"while (true) { echo 1 . PHP_EOL; sleep(1); }\" ');"`

**Comment by azjezz** [comment]
i have made code structure and a simple server with the router , you can find it here : 
https://github.com/azjezz/php-lightserver-alpha/invitations

**Comment by azjezz** [comment]
i don't really have time to do much now, but you got the idea,
